name: Crawler test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_for_crawler_on_MacOS:
    timeout-minutes: 25
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      run: |
        brew install docker
        docker-compose up
        
  test_for_crawler_on_LinuxUbuntu:
    timeout-minutes: 25
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run build
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install docker
        docker-compose up
