name: Crawler build test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_for_crawler_build_on_Ubuntu:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run build
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
    
  test_for_crawler_build_on_MacOS:
    timeout-minutes: 10
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Docker and Docker Compose
      run: |
        brew install --cask docker
    
    - name: Run Docker Compose
      run: |
        open /Applications/Docker.app
        docker-compose -f "docker-compose.yml" up -d --build
